In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("Eva.1.csv")

In [4]:
df

            Date  Sales    Item_ID
0       01-11-23      1  461100003
1       01-11-23      1  661100003
2       01-11-23      2  651100005
3       01-11-23      1  671100005
4       01-11-23      2  681100005
...          ...    ...        ...
316379  31-01-24      3  649900381
316380  31-01-24      2  679900381
316381  31-01-24      1  689900381
316382  31-01-24      1  809900381
316383  31-01-24     38  819900381

[316384 rows x 3 columns]

In [5]:
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

# Load the data
data = pd.read_csv('Eva.1.csv')

# Preprocess the data
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%y')
data.set_index('Date', inplace=True)
data['Sales'] = pd.to_numeric(data['Sales'])

# Aggregate the data by Item_ID
grouped_data = data.groupby('Item_ID')['Sales'].resample('D').sum().unstack(fill_value=0)

# Check for stationarity
# Perform the ADF test, plot ACF and PACF
# (Code not shown)

# Difference the data if needed
# (Code not shown)

# Identify parameters using ACF and PACF plots
# (Code not shown)

# Train the SARIMA model
item_id = 461100003  # Example Item_ID
train_data = grouped_data[item_id][:-7]  # Using all data except the last 7 days for training

model = SARIMAX(train_data, order=(p, d, q), seasonal_order=(P, D, Q, m))
results = model.fit()

# Validate the model
# (Code not shown)

# Forecast sales for the next 7 days
forecast = results.forecast(steps=7)

print(forecast)

KeyError: 'Item_ID'